name: flitro
description: The Instagram effect creator.

#versionnumber+buildbumber
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_colorpicker: ^0.3.4
  provider: ^4.0.5+1
  image_picker: ^0.6.6+4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: cocogoose
      fonts:
        - asset: assets/fonts/cocogoose.ttf
    - family: chicken
      fonts:
        - asset: assets/fonts/chicken.ttf
    - family: cherolina
      fonts:
        - asset: assets/fonts/cherolina.ttf
    - family: longshot
      fonts:
        - asset: assets/fonts/longshot.ttf
    - family: oldlondon
      fonts:
        - asset: assets/fonts/oldlondon.ttf
